Add License info

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,31 @@
 #!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir> <env-dir>
+#
+# Copyright 2016 Google Inc.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+#     Unless required by applicable law or agreed to in writing, software
+#     distributed under the License is distributed on an "AS IS" BASIS,
+#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+#     See the License for the specific language governing permissions and
+#     limitations under the License.
+#
+# Usage:
+#   bin/compile <build-dir> <cache-dir> <env-dir>
+#
+# Notes:
+# This script takes the build, cache, and environment directories are arugments.
+# Cache is persisted between builds. The full application should be built in the
+# build directory. This is a temporary directory that the Heroku built system
+# will package into a slug with a different path, so symlinks can cause
+# problems.
+#
+# We circumvent this difficulty by building the deploy jar and copying that to
+# the build directory.
 
 indent() {
   sed -u 's/^/       /'
@@ -14,33 +40,35 @@ CACHE_DIR=$2
 ENV_DIR=$3
 
 # default to Bazel version 0.3.0
-if [ ! -v BAZEL_VERSION ]; then
+if [[ ! -v BAZEL_VERSION ]]; then
   BAZEL_VERSION="0.3.0"
 fi
 
 # install Java 1.8
-JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-"https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz"}
+JVM_BUILDPACK="https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz"
+JVM_COMMON_BUILDPACK=${JVM_COMMON_BUILDPACK:-${JVM_BUILDPACK}}
 mkdir -p /tmp/jvm-common
-curl --retry 3 --silent --location $JVM_COMMON_BUILDPACK | tar xzm -C /tmp/jvm-common --strip-components=1
+curl --retry 3 --silent --location $JVM_COMMON_BUILDPACK \
+  | tar xzm -C /tmp/jvm-common --strip-components=1
 . /tmp/jvm-common/bin/util
 . /tmp/jvm-common/bin/java
 
-install_java_with_overlay ${BUILD_DIR}
-
-export JAVA_HOME="${BUILD_DIR}/.jdk"
+install_java_with_overlay ${BUILD_DIR} | indent
 
 # Create the CACHE_DIR if it doesn't exists.
-if [ ! -d ${CACHE_DIR} ]; then
+if [[ ! -d ${CACHE_DIR} ]]; then
   mkdir ${CACHE_DIR}
 fi
 
 # Fetch the Bazel installer
-URL=https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
-echo "-----> Downloading bazel from $URL"
+# TODO: consider keeping the Bazel and Java installs in cache.
+URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/"
+URL+="bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
+echo "-----> Downloading Bazel from $URL"
 export BAZEL_INSTALLER=${CACHE_DIR}/install.sh
 curl -L -o ${BAZEL_INSTALLER} ${URL}
-if [ $? -ne 0 ]; then
-  echo "download failed"
+if [[ $? -ne 0 ]]; then
+  echo "download failed" >&2
   exit 1
 fi
 
@@ -52,16 +80,17 @@ if ! [ echo $PATH | grep -q "${BASE}" ]; then
   export PATH
 fi
 
-# Install bazel inside ${BASE}
-echo "installing bazel" | indent
+# Install Bazel inside ${BASE}
+echo "-----> Installing Bazel"
 bash "${BAZEL_INSTALLER}" \
   --base="${BASE}" \
   --bazelrc="${HOME}/bazel.bazelrc" \
-  --bin="${BASE}/binary"
+  --bin="${BASE}/binary" | indent
 
 # Custom bazelrc file for Docker
 echo -e "\nstartup --batch" >> $BUILD_DIR/bazel.bazelrc
-echo -e "\nbuild --spawn_strategy=standalone --genrule_strategy=standalone" >> $BUILD_DIR/bazel.bazelrc
+echo -e "\nbuild --spawn_strategy=standalone --genrule_strategy=standalone" \
+  >> $BUILD_DIR/bazel.bazelrc
 
 # Build app
 BAZEL="${BASE}/binary/bazel --bazelrc=${BUILD_DIR}/bazel.bazelrc"
@@ -69,7 +98,8 @@ cd $BUILD_DIR
 ${BAZEL} clean
 ${BAZEL} build -c opt $(cat build_path)
 
-# Find absolute path to deploy jar. For whatever reason. Heroku doesn't like the bazel symlinks.
+# Find absolute path to deploy jar. For whatever reason. Heroku doesn't like the
+# Bazel symlinks.
 BAZEL_BIN=$(ls -l | grep "bazel-bin" | sed 's/.* -> //')
 
 # Copy the deploy jar to the build directory
